export const designTokens = {
    colors: {
        bg: 'var(--background)',
        surface: 'var(--surface)',
        'surface-2': 'var(--surface-2)',
        'surface-3': 'var(--surface-3)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        muted: 'var(--text-muted)',
        subtle: 'var(--text-subtle)',
        accent: 'var(--accent)',
        'accent-fg': 'var(--accent-foreground)',
        gold: 'var(--accent)',
        danger: 'var(--danger)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        info: 'var(--info)',
    },
    radius: {
        xs: 'var(--radius-xs, 6px)',
        sm: 'var(--radius-sm, 8px)',
        md: 'var(--radius-md, 12px)',
        lg: 'var(--radius-lg, 16px)',
        xl: 'var(--radius-xl, 20px)',
    },
    spacing: {
        pageGap: 'var(--crm-page-gap, 18px)',
        panelGap: 'var(--crm-panel-gap, 14px)',
    },
} as const;
