export const theme = {
    colors: {
        primary: '#fcb12d',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        surface: 'var(--surface)',
        surface2: 'var(--surface-2)',
        surface3: 'var(--surface-3)',
        border: 'var(--border)',
        borderStrong: 'var(--border-strong)',
        text: 'var(--foreground)',
        muted: 'var(--text-muted)',
        subtle: 'var(--text-subtle)',
        danger: 'var(--danger)',
        warning: 'var(--warning)',
        success: 'var(--success)',
        info: 'var(--info)',
        gold: 'var(--accent)',
        goldHover: 'var(--accent-hover)',
        goldPressed: 'var(--accent-pressed)',
        goldForeground: 'var(--accent-foreground)',
        focusRing: 'var(--focus-ring)',
        sidebarBg: 'var(--crm-bg-2, #0b0c0d)',
        sidebarBorder: 'var(--crm-border, #2b2921)',
        sidebarText: 'var(--crm-text-muted, #a9a294)',
        sidebarActive: 'var(--crm-gold, #fcb12d)',
        sidebarHover: 'rgba(255,255,255,0.04)',
        tableBg: 'var(--surface)',
        tableBorder: 'var(--border)',
        tableRowHover: 'color-mix(in srgb, var(--surface-2) 70%, transparent)',
    },
    radius: {
        sm: '6px',
        md: '10px',
        lg: '14px',
        xl: '18px',
    },
    spacing: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '10px',
        xl: '12px',
        '2xl': '16px',
        '3xl': '20px',
    },
    fontSize: {
        xs: '11px',
        sm: '12px',
        base: '13px',
        md: '14px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
    },
    shadow: {
        card: '0 1px 2px rgb(15 23 42 / 0.05)',
        dropdown: '0 4px 12px rgb(15 23 42 / 0.08)',
        modal: '0 20px 25px -5px rgb(15 23 42 / 0.12), 0 8px 10px -6px rgb(15 23 42 / 0.12)',
    },
} as const;

export type Theme = typeof theme;
