<?php

return [
    /*
     * The catalogue is the single source of truth for application abilities.
     * Labels live here so the user administration module can render roles
     * without duplicating permission names in React pages.
     */
    'permissions' => [
        'dashboard.view' => ['group' => 'dashboard', 'label' => 'Voir le tableau de bord'],

        'clients.view' => ['group' => 'clients', 'label' => 'Voir les clients'],
        'clients.create' => ['group' => 'clients', 'label' => 'Créer des clients'],
        'clients.update' => ['group' => 'clients', 'label' => 'Modifier des clients'],
        'clients.delete' => ['group' => 'clients', 'label' => 'Supprimer des clients'],
        'clients.status.update' => ['group' => 'clients', 'label' => 'Modifier le statut des clients'],
        'clients.cin.scan' => ['group' => 'clients', 'label' => 'Analyser une CIN'],

        'intermediaries.view' => ['group' => 'intermediaries', 'label' => 'Voir les intermédiaires'],
        'intermediaries.create' => ['group' => 'intermediaries', 'label' => 'Créer des intermédiaires'],
        'intermediaries.update' => ['group' => 'intermediaries', 'label' => 'Modifier des intermédiaires'],
        'intermediaries.delete' => ['group' => 'intermediaries', 'label' => 'Supprimer des intermédiaires'],

        'dossiers.view' => ['group' => 'dossiers', 'label' => 'Voir les dossiers'],
        'dossiers.create' => ['group' => 'dossiers', 'label' => 'Créer des dossiers'],
        'dossiers.update' => ['group' => 'dossiers', 'label' => 'Modifier des dossiers'],
        'dossiers.delete' => ['group' => 'dossiers', 'label' => 'Supprimer des dossiers'],
        'dossiers.workflow.update' => ['group' => 'dossiers', 'label' => 'Mettre à jour le workflow dossier'],

        'documents.view' => ['group' => 'documents', 'label' => 'Voir les documents'],
        'documents.create' => ['group' => 'documents', 'label' => 'Ajouter des documents'],
        'documents.update' => ['group' => 'documents', 'label' => 'Modifier des documents'],
        'documents.delete' => ['group' => 'documents', 'label' => 'Supprimer des documents'],
        'documents.download' => ['group' => 'documents', 'label' => 'Télécharger des documents'],
        'documents.print' => ['group' => 'documents', 'label' => 'Imprimer des documents'],
        'documents.replace' => ['group' => 'documents', 'label' => 'Remplacer des documents'],

        'contracts.view' => ['group' => 'contracts', 'label' => 'Voir les contrats'],
        'contracts.create' => ['group' => 'contracts', 'label' => 'Créer des contrats'],
        'contracts.update' => ['group' => 'contracts', 'label' => 'Modifier des contrats'],
        'contracts.delete' => ['group' => 'contracts', 'label' => 'Supprimer des contrats'],
        'contracts.generate' => ['group' => 'contracts', 'label' => 'Générer des contrats'],
        'contracts.download' => ['group' => 'contracts', 'label' => 'Télécharger des contrats'],
        'contracts.print' => ['group' => 'contracts', 'label' => 'Imprimer des contrats'],

        'archive.view' => ['group' => 'archive', 'label' => 'Voir les archives'],
        'archive.create' => ['group' => 'archive', 'label' => 'Créer des archives'],
        'archive.update' => ['group' => 'archive', 'label' => 'Modifier des archives'],
        'archive.checkout' => ['group' => 'archive', 'label' => 'Sortir une archive'],
        'archive.checkin' => ['group' => 'archive', 'label' => 'Retourner une archive'],
        'archive.delete' => ['group' => 'archive', 'label' => 'Supprimer des archives'],

        'finance.view' => ['group' => 'finance', 'label' => 'Voir la finance'],
        'finance.documents.create' => ['group' => 'finance', 'label' => 'Créer devis et factures'],
        'finance.documents.update' => ['group' => 'finance', 'label' => 'Modifier devis et factures'],
        'finance.documents.issue' => ['group' => 'finance', 'label' => 'Émettre devis et factures'],
        'finance.documents.cancel' => ['group' => 'finance', 'label' => 'Annuler devis et factures'],
        'finance.documents.delete' => ['group' => 'finance', 'label' => 'Supprimer devis et factures'],
        'finance.payments.view' => ['group' => 'finance', 'label' => 'Voir les paiements'],
        'finance.payments.create' => ['group' => 'finance', 'label' => 'Enregistrer des paiements'],
        'finance.payments.update' => ['group' => 'finance', 'label' => 'Modifier des paiements'],
        'finance.payments.reverse' => ['group' => 'finance', 'label' => 'Annuler des paiements'],
        'finance.expenses.view' => ['group' => 'finance', 'label' => 'Voir les dépenses'],
        'finance.expenses.create' => ['group' => 'finance', 'label' => 'Créer des dépenses'],
        'finance.expenses.update' => ['group' => 'finance', 'label' => 'Modifier des dépenses'],
        'finance.expenses.delete' => ['group' => 'finance', 'label' => 'Supprimer des dépenses'],
        'finance.templates.view' => ['group' => 'finance', 'label' => 'Voir les modèles financiers'],
        'finance.templates.manage' => ['group' => 'finance', 'label' => 'Gérer les modèles financiers'],
        'finance.reports.export' => ['group' => 'finance', 'label' => 'Exporter les rapports financiers'],
        'finance.settings.view' => ['group' => 'finance', 'label' => 'Voir les paramètres financiers'],
        'finance.settings.update' => ['group' => 'finance', 'label' => 'Modifier les paramètres financiers'],

        'tasks.view' => ['group' => 'tasks', 'label' => 'Voir les tâches'],
        'tasks.create' => ['group' => 'tasks', 'label' => 'Créer des tâches'],
        'tasks.update' => ['group' => 'tasks', 'label' => 'Modifier des tâches'],
        'tasks.delete' => ['group' => 'tasks', 'label' => 'Supprimer des tâches'],
        'tasks.assign' => ['group' => 'tasks', 'label' => 'Assigner des tâches'],
        'tasks.complete' => ['group' => 'tasks', 'label' => 'Terminer des tâches'],

        'calendar.view' => ['group' => 'calendar', 'label' => 'Voir le calendrier'],
        'calendar.create' => ['group' => 'calendar', 'label' => 'Créer des événements'],
        'calendar.update' => ['group' => 'calendar', 'label' => 'Modifier des événements'],
        'calendar.delete' => ['group' => 'calendar', 'label' => 'Supprimer des événements'],

        'inbox.view' => ['group' => 'inbox', 'label' => 'Voir la messagerie'],
        'inbox.manage' => ['group' => 'inbox', 'label' => 'Gérer la messagerie'],
        'notifications.view' => ['group' => 'notifications', 'label' => 'Voir les notifications'],
        'notifications.manage' => ['group' => 'notifications', 'label' => 'Gérer les notifications'],
        'reports.operations.view' => ['group' => 'reports', 'label' => 'Voir les rapports opérationnels'],
        'reports.workload.view' => ['group' => 'reports', 'label' => 'Voir la charge de travail'],

        'users.view' => ['group' => 'users', 'label' => 'Voir les utilisateurs'],
        'users.create' => ['group' => 'users', 'label' => 'Créer des utilisateurs'],
        'users.update' => ['group' => 'users', 'label' => 'Modifier des utilisateurs'],
        'users.delete' => ['group' => 'users', 'label' => 'Supprimer des utilisateurs'],
        'users.roles.manage' => ['group' => 'users', 'label' => 'Gérer les rôles et permissions'],
        'users.access.manage' => ['group' => 'users', 'label' => 'Gérer les accès utilisateurs'],
        'users.password.reset' => ['group' => 'users', 'label' => 'Envoyer une réinitialisation de mot de passe'],

        'settings.view' => ['group' => 'settings', 'label' => 'Voir les paramètres'],
        'settings.update' => ['group' => 'settings', 'label' => 'Modifier les paramètres'],
        'qa.view' => ['group' => 'qa', 'label' => 'Voir les contrôles qualité'],

        'project-design.view' => ['group' => 'project-design', 'label' => 'Voir les plans'],
        'project-design.create-folder' => ['group' => 'project-design', 'label' => 'Créer des dossiers de plans'],
        'project-design.update-folder' => ['group' => 'project-design', 'label' => 'Modifier des dossiers de plans'],
        'project-design.delete-folder' => ['group' => 'project-design', 'label' => 'Supprimer des dossiers de plans'],
        'project-design.create-file' => ['group' => 'project-design', 'label' => 'Créer des fichiers de plans'],
        'project-design.update-file' => ['group' => 'project-design', 'label' => 'Modifier des fichiers de plans'],
        'project-design.upload' => ['group' => 'project-design', 'label' => 'Téléverser des plans'],
        'project-design.download-source' => ['group' => 'project-design', 'label' => 'Télécharger les sources de plans'],
        'project-design.create-version' => ['group' => 'project-design', 'label' => 'Créer une version de plan'],
        'project-design.submit-review' => ['group' => 'project-design', 'label' => 'Soumettre des plans pour revue'],
        'project-design.review' => ['group' => 'project-design', 'label' => 'Revoir des plans'],
        'project-design.annotate' => ['group' => 'project-design', 'label' => 'Annoter des plans'],
        'project-design.create-remark' => ['group' => 'project-design', 'label' => 'Créer des remarques'],
        'project-design.assign-remark' => ['group' => 'project-design', 'label' => 'Assigner des remarques'],
        'project-design.address-remark' => ['group' => 'project-design', 'label' => 'Répondre aux remarques'],
        'project-design.verify-remark' => ['group' => 'project-design', 'label' => 'Vérifier des remarques'],
        'project-design.reopen-remark' => ['group' => 'project-design', 'label' => 'Rouvrir des remarques'],
        'project-design.approve' => ['group' => 'project-design', 'label' => 'Approuver des plans'],
        'project-design.request-changes' => ['group' => 'project-design', 'label' => 'Demander des corrections'],
        'project-design.archive' => ['group' => 'project-design', 'label' => 'Archiver des plans'],
        'project-design.restore' => ['group' => 'project-design', 'label' => 'Restaurer des plans'],
        'project-design.delete' => ['group' => 'project-design', 'label' => 'Supprimer des plans'],
        'project-design.manage' => ['group' => 'project-design', 'label' => 'Gérer les plans'],
    ],

    'legacy_aliases' => [
        'dashboard.view' => ['view dashboard'],
        'clients.*' => ['manage clients'],
        'intermediaries.*' => ['manage clients'],
        'dossiers.*' => ['manage dossiers'],
        'documents.*' => ['manage documents'],
        'contracts.*' => ['manage contracts'],
        'archive.*' => ['manage archives'],
        'tasks.view' => ['view tasks', 'manage tasks'],
        'tasks.create' => ['manage tasks'],
        'tasks.update' => ['manage tasks'],
        'tasks.delete' => ['manage tasks'],
        'tasks.assign' => ['manage tasks'],
        'tasks.complete' => ['manage tasks'],
        'inbox.view' => ['view inbox', 'manage inbox'],
        'inbox.manage' => ['manage inbox'],
        'notifications.view' => ['view notifications', 'manage notifications'],
        'notifications.manage' => ['manage notifications'],
        'reports.workload.view' => ['view workload'],
        'reports.operations.view' => ['view operations reports'],
        'users.*' => ['manage users'],
        'qa.view' => ['view qa'],
        'project-design.*' => ['project_design'],
    ],

    /*
     * The User Management permission editor uses these action sets when a
     * manager creates a custom account. Keep this mapping here, next to the
     * permission catalogue, so the UI never invents authorization rules.
     */
    'access_modules' => [
        'Clients' => [
            'view' => ['clients.view', 'intermediaries.view'],
            'edit' => ['clients.create', 'clients.update', 'clients.status.update', 'clients.cin.scan', 'intermediaries.create', 'intermediaries.update'],
            'delete' => ['clients.delete', 'intermediaries.delete'],
        ],
        'Projects' => [
            'view' => ['dossiers.view', 'project-design.view'],
            'edit' => ['dossiers.create', 'dossiers.update', 'dossiers.workflow.update', 'project-design.create-folder', 'project-design.update-folder', 'project-design.create-file', 'project-design.update-file', 'project-design.upload', 'project-design.create-version', 'project-design.annotate', 'project-design.create-remark', 'project-design.address-remark'],
            'delete' => ['dossiers.delete', 'project-design.delete-folder', 'project-design.delete'],
        ],
        'Documents' => [
            'view' => ['documents.view'],
            'edit' => ['documents.create', 'documents.update', 'documents.replace', 'documents.download', 'documents.print'],
            'delete' => ['documents.delete'],
        ],
        'Contracts' => [
            'view' => ['contracts.view'],
            'edit' => ['contracts.create', 'contracts.update', 'contracts.generate', 'contracts.download', 'contracts.print'],
            'delete' => ['contracts.delete'],
        ],
        'Finance' => [
            'view' => ['finance.view', 'finance.payments.view', 'finance.expenses.view', 'finance.templates.view', 'finance.settings.view'],
            'edit' => ['finance.documents.create', 'finance.documents.update', 'finance.documents.issue', 'finance.documents.cancel', 'finance.payments.create', 'finance.payments.update', 'finance.payments.reverse', 'finance.expenses.create', 'finance.expenses.update', 'finance.templates.manage', 'finance.settings.update', 'finance.reports.export'],
            'delete' => ['finance.documents.delete', 'finance.expenses.delete'],
        ],
        'Tasks' => [
            'view' => ['tasks.view'],
            'edit' => ['tasks.create', 'tasks.update', 'tasks.assign', 'tasks.complete'],
            'delete' => ['tasks.delete'],
        ],
        'Calendar' => [
            'view' => ['calendar.view'],
            'edit' => ['calendar.create', 'calendar.update'],
            'delete' => [],
        ],
        'Inbox' => [
            'view' => ['inbox.view'],
            'edit' => ['inbox.manage'],
            'delete' => [],
        ],
        'Reports' => [
            'view' => ['reports.workload.view', 'reports.operations.view'],
            'edit' => [],
            'delete' => [],
        ],
        'Archives' => [
            'view' => ['archive.view'],
            'edit' => ['archive.create', 'archive.update', 'archive.checkout', 'archive.checkin'],
            'delete' => ['archive.delete'],
        ],
    ],

    'route_permissions' => [
        'dashboard' => 'dashboard.view',
        // Global search has no single route-level ability. The controller filters
        // every result category by its module permission and tenant scope.
        'api.clients.search' => 'clients.view',
        'api.clients.projects' => 'clients.view',
        'frontend-qa.index' => 'qa.view',
        'backend-qa.index' => 'qa.view',

        'clients.index' => 'clients.view',
        'clients.show' => 'clients.view',
        'clients.store' => 'clients.create',
        'clients.update' => 'clients.update',
        'clients.destroy' => 'clients.delete',
        'clients.status.update' => 'clients.status.update',
        'clients.scan-cin' => 'clients.cin.scan',
        'intermediaries.index' => 'intermediaries.view',
        'intermediaries.show' => 'intermediaries.view',
        'intermediaries.store' => 'intermediaries.create',
        'intermediaries.update' => 'intermediaries.update',
        'intermediaries.destroy' => 'intermediaries.delete',
        'dossiers.index' => 'dossiers.view',
        'dossiers.show' => 'dossiers.view',
        'dossiers.store' => 'dossiers.create',
        'dossiers.update' => 'dossiers.update',
        'dossiers.destroy' => 'dossiers.delete',
        'dossiers.workflow-requirements.update' => 'dossiers.workflow.update',
        'documents.index' => 'documents.view',
        'documents.store' => 'documents.create',
        'documents.status' => 'documents.update',
        'documents.destroy' => 'documents.delete',
        'documents.replace' => 'documents.replace',
        'documents.view' => 'documents.view',
        'documents.print' => 'documents.print',
        'documents.download' => 'documents.download',
        'documents.content' => 'documents.view',
        'contracts.index' => 'contracts.view',
        'contracts.store' => 'contracts.create',
        'contracts.update' => 'contracts.update',
        'contracts.destroy' => 'contracts.delete',
        'contracts.generate' => 'contracts.generate',
        'contracts.export-pdf' => 'contracts.generate',
        'contracts.signed' => 'contracts.update',
        'contracts.print' => 'contracts.print',
        'contracts.download.generated' => 'contracts.download',
        'contracts.download.pdf' => 'contracts.download',
        'contracts.preview.pdf' => 'contracts.view',
        'archives.index' => 'archive.view',
        'archives.show' => 'archive.view',
        'archives.count' => 'archive.view',
        'archives.reports' => 'archive.view',
        'archives.boxes.contents' => 'archive.view',
        'archives.store' => 'archive.create',
        'archives.update' => 'archive.update',
        'archives.status' => 'archive.update',
        'archives.mark-lost' => 'archive.update',
        'archives.move' => 'archive.update',
        'archives.bulk.status' => 'archive.update',
        'archives.bulk.move' => 'archive.update',
        'archives.checkout' => 'archive.checkout',
        'archives.return' => 'archive.checkin',
        'archives.destroy' => 'archive.delete',
        'admin.users.audit-logs' => 'users.view',
        'admin.users.store' => 'users.create',
        'admin.users.destroy' => 'users.delete',
        'admin.users.bulk.destroy' => 'users.delete',
        'admin.users.role' => 'users.roles.manage',
        'admin.users.permissions' => 'users.roles.manage',
        'admin.users.bulk.role' => 'users.roles.manage',
        'admin.users.access.update' => 'users.access.manage',
        'admin.users.bulk.suspend' => 'users.access.manage',
        'admin.users.invite' => 'users.create',
        'admin.users.invite.bulk.validate' => 'users.create',
        'admin.users.invite.bulk' => 'users.create',
        'admin.users.invite.resend' => 'users.create',
        'admin.users.password-reset' => 'users.password.reset',
        'finance.index' => 'finance.view',
        'finance.monthly-summary.export-pdf' => 'finance.reports.export',
        'finance.monthly-summary.export-excel' => 'finance.reports.export',
        'finance.monthly-summary.export-csv' => 'finance.reports.export',
        'finance.templates.index' => 'finance.templates.view',
        'finance.templates.show' => 'finance.templates.view',
        'finance.templates.preview' => 'finance.templates.view',
        'finance.templates.versions.index' => 'finance.templates.view',
        'finance.templates.store' => 'finance.templates.manage',
        'finance.templates.reset' => 'finance.templates.manage',
        'finance.templates.update' => 'finance.templates.manage',
        'finance.templates.rename' => 'finance.templates.manage',
        'finance.templates.destroy' => 'finance.templates.manage',
        'finance.templates.duplicate' => 'finance.templates.manage',
        'finance.templates.default' => 'finance.templates.manage',
        'finance.templates.versions.store' => 'finance.templates.manage',
        'finance.templates.versions.restore' => 'finance.templates.manage',
        'finance.templates.versions.destroy' => 'finance.templates.manage',
        'finance.documents.index' => 'finance.view',
        'finance.documents.show' => 'finance.view',
        'finance.documents.preview-html' => 'finance.view',
        'finance.documents.view' => 'finance.view',
        'finance.documents.view-pdf' => 'finance.view',
        'finance.documents.print' => 'finance.view',
        'finance.documents.download' => 'finance.view',
        'finance.documents.download-excel' => 'finance.view',
        'finance.documents.download-pdf' => 'finance.view',
        'finance.documents.store' => 'finance.documents.create',
        'finance.documents.preview-draft' => 'finance.documents.create',
        'finance.documents.update' => 'finance.documents.update',
        'finance.documents.destroy' => 'finance.documents.delete',
        'finance.documents.generate' => 'finance.documents.issue',
        'finance.documents.generate-pdf' => 'finance.documents.issue',
        'finance.documents.generate-excel' => 'finance.documents.issue',
        'finance.documents.reveal-generated-files' => 'finance.view',
        'finance.documents.accept' => 'finance.documents.update',
        'finance.documents.reject' => 'finance.documents.update',
        'finance.documents.cancel' => 'finance.documents.cancel',
        'finance.documents.convert-to-invoice' => 'finance.documents.create',
        'finance.payments.index' => 'finance.payments.view',
        'finance.payments.store' => 'finance.payments.create',
        'finance.payments.update' => 'finance.payments.update',
        'finance.payments.destroy' => 'finance.payments.reverse',
        'finance.expenses.index' => 'finance.expenses.view',
        'finance.expenses.store' => 'finance.expenses.create',
        'finance.expenses.update' => 'finance.expenses.update',
        'finance.expenses.destroy' => 'finance.expenses.delete',
        'finance.settings.update' => 'finance.settings.update',
        'finance.settings.reset' => 'finance.settings.update',
        'finance.settings.logo.store' => 'finance.settings.update',
        'finance.settings.logo.destroy' => 'finance.settings.update',

        'settings.index' => 'archive.view',
        'settings.cities.store' => 'archive.update',
        'settings.cities.update' => 'archive.update',
        'settings.cities.destroy' => 'archive.delete',

        'dossiers.project-design.*' => 'project-design.view',
        'project-design.assets.*' => 'project-design.view',
        'tus.*' => 'project-design.upload',

        'tasks.index' => 'tasks.view',
        'tasks.show' => 'tasks.view',
        'tasks.detail' => 'tasks.view',
        'tasks.comments.index' => 'tasks.view',
        'tasks.checklist.index' => 'tasks.view',
        'tasks.suggestions.index' => 'tasks.view',
        'tasks.store' => 'tasks.create',
        'tasks.suggestions.create-task' => 'tasks.create',
        'tasks.update' => 'tasks.update',
        'tasks.comments.store' => 'tasks.update',
        'tasks.comments.destroy' => 'tasks.update',
        'tasks.checklist.store' => 'tasks.update',
        'tasks.checklist.destroy' => 'tasks.update',
        'tasks.attachments.store' => 'tasks.update',
        'tasks.attachments.destroy' => 'tasks.update',
        'tasks.suggestions.dismiss' => 'tasks.update',
        'tasks.status' => 'tasks.complete',
        'tasks.checklist.toggle' => 'tasks.complete',
        'tasks.destroy' => 'tasks.delete',

        'inbox.index' => 'inbox.view',
        'inbox.archived' => 'inbox.view',
        'inbox.list' => 'inbox.view',
        'inbox.show' => 'inbox.view',
        'inbox.search' => 'inbox.view',
        'inbox.attachments' => 'inbox.view',
        'inbox.attachments.view' => 'inbox.view',
        'inbox.attachments.download' => 'inbox.view',
        'inbox.typing' => 'inbox.view',
        'inbox.typing.users' => 'inbox.view',
        'inbox.preferences' => 'inbox.view',
        'inbox.mark-unread' => 'inbox.view',
        'inbox.store' => 'inbox.manage',
        'inbox.update' => 'inbox.manage',
        'inbox.participants.add' => 'inbox.manage',
        'inbox.participants.remove' => 'inbox.manage',
        'inbox.messages.store' => 'inbox.manage',
        'inbox.messages.update' => 'inbox.manage',
        'inbox.messages.destroy' => 'inbox.manage',
        'inbox.messages.forward' => 'inbox.manage',
        'inbox.archive' => 'inbox.view',
        'inbox.unarchive' => 'inbox.view',

        'notifications.index' => 'notifications.view',
        'notifications.read' => 'notifications.view',
        'notifications.read-all' => 'notifications.view',
        'workload.index' => 'reports.workload.view',
        'operations.reports.index' => 'reports.operations.view',

        'calendar.index' => 'calendar.view',
        'calendar.events.show' => 'calendar.view',
        'calendar.events.conflicts' => 'calendar.view',
        'calendar.reminders.snooze' => 'calendar.view',
        'calendar.reminders.dismiss' => 'calendar.view',
        'calendar.events.store' => 'calendar.create',
        'calendar.events.update' => 'calendar.update',
        'calendar.events.move' => 'calendar.update',
        'calendar.events.resize' => 'calendar.update',
        'calendar.events.participants.store' => 'calendar.update',
        'calendar.events.participants.destroy' => 'calendar.update',
        'calendar.events.reminders.store' => 'calendar.update',
        'calendar.events.destroy' => 'calendar.delete',
    ],
];
