<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Design Format Capability Registry
    |--------------------------------------------------------------------------
    |
    | This is the single source of truth for all supported design file formats.
    | Frontend capability data is derived from this config through the API.
    | Do not duplicate format lists in components, validators, or jobs.
    |
    */

    'formats' => [

        // ─── PDF ────────────────────────────────────────────────────────
        'pdf' => [
            'extension' => 'pdf',
            'label' => 'PDF Document',
            'mime_types' => ['application/pdf'],
            'application' => 'other',
            'category' => 'review',
            'asset_type' => 'review_pdf',
            'preview_strategy' => 'pdf',
            'direct_browser_preview' => true,
            'conversion_provider' => null,
            'supported_viewer' => 'pdf',
            'supports_2d' => true,
            'supports_3d' => false,
            'supports_sheets' => true,
            'supports_layers' => false,
            'supports_properties' => false,
            'supports_measurement' => false,
            'supports_annotations' => true,
            'supports_comparison' => false,
            'max_size_bytes' => 500 * 1024 * 1024,
            'icon' => 'file-text',
            'fallback_message' => 'PDF preview requires a compatible browser.',
        ],

        // ─── Images ─────────────────────────────────────────────────────
        'png' => [
            'extension' => 'png',
            'label' => 'PNG Image',
            'mime_types' => ['image/png'],
            'application' => 'other',
            'category' => 'review',
            'asset_type' => 'image',
            'preview_strategy' => 'image',
            'direct_browser_preview' => true,
            'conversion_provider' => null,
            'supported_viewer' => 'image',
            'supports_2d' => true,
            'supports_3d' => false,
            'supports_sheets' => false,
            'supports_layers' => false,
            'supports_properties' => false,
            'supports_measurement' => false,
            'supports_annotations' => true,
            'supports_comparison' => false,
            'max_size_bytes' => 200 * 1024 * 1024,
            'icon' => 'image',
            'fallback_message' => null,
        ],

        'jpg' => [
            'extension' => 'jpg',
            'label' => 'JPEG Image',
            'mime_types' => ['image/jpeg', 'image/jpg'],
            'application' => 'other',
            'category' => 'review',
            'asset_type' => 'image',
            'preview_strategy' => 'image',
            'direct_browser_preview' => true,
            'conversion_provider' => null,
            'supported_viewer' => 'image',
            'supports_2d' => true,
            'supports_3d' => false,
            'supports_sheets' => false,
            'supports_layers' => false,
            'supports_properties' => false,
            'supports_measurement' => false,
            'supports_annotations' => true,
            'supports_comparison' => false,
            'max_size_bytes' => 200 * 1024 * 1024,
            'icon' => 'image',
            'fallback_message' => null,
        ],

        'webp' => [
            'extension' => 'webp',
            'label' => 'WebP Image',
            'mime_types' => ['image/webp'],
            'application' => 'other',
            'category' => 'review',
            'asset_type' => 'image',
            'preview_strategy' => 'image',
            'direct_browser_preview' => true,
            'conversion_provider' => null,
            'supported_viewer' => 'image',
            'supports_2d' => true,
            'supports_3d' => false,
            'supports_sheets' => false,
            'supports_layers' => false,
            'supports_properties' => false,
            'supports_measurement' => false,
            'supports_annotations' => true,
            'supports_comparison' => false,
            'max_size_bytes' => 200 * 1024 * 1024,
            'icon' => 'image',
            'fallback_message' => null,
        ],

        'tiff' => [
            'extension' => 'tiff',
            'label' => 'TIFF Image',
            'mime_types' => ['image/tiff', 'image/tif'],
            'application' => 'other',
            'category' => 'review',
            'asset_type' => 'image',
            'preview_strategy' => 'server-conversion',
            'direct_browser_preview' => false,
            'conversion_provider' => 'internal',
            'supported_viewer' => 'image',
            'supports_2d' => true,
            'supports_3d' => false,
            'supports_sheets' => false,
            'supports_layers' => false,
            'supports_properties' => false,
            'supports_measurement' => false,
            'supports_annotations' => true,
            'supports_comparison' => false,
            'max_size_bytes' => 200 * 1024 * 1024,
            'icon' => 'image',
            'fallback_message' => 'TIFF images are converted to a browser-compatible format for preview.',
        ],

        // ─── IFC ────────────────────────────────────────────────────────
        'ifc' => [
            'extension' => 'ifc',
            'label' => 'IFC Model',
            'mime_types' => ['application/x-step', 'application/x-ifc', 'application/ifc', 'application/x-ifc'],
            'application' => 'ifc',
            'category' => 'review',
            'asset_type' => 'ifc',
            'preview_strategy' => 'ifc',
            'direct_browser_preview' => false,
            'conversion_provider' => 'internal',
            'supported_viewer' => 'ifc',
            'supports_2d' => false,
            'supports_3d' => true,
            'supports_sheets' => false,
            'supports_layers' => true,
            'supports_properties' => true,
            'supports_measurement' => true,
            'supports_annotations' => true,
            'supports_comparison' => false,
            'max_size_bytes' => 500 * 1024 * 1024,
            'icon' => 'cube',
            'fallback_message' => 'IFC models are converted to fragments for 3D browser preview.',
        ],

        // ─── DWG ────────────────────────────────────────────────────────
        'dwg' => [
            'extension' => 'dwg',
            'label' => 'AutoCAD Drawing',
            'mime_types' => ['application/acad', 'application/x-acad', 'image/vnd.dwg', 'application/dwg', 'application/x-dwg'],
            'application' => 'autocad',
            'category' => 'source',
            'asset_type' => 'source',
            'preview_strategy' => 'autodesk-aps',
            'direct_browser_preview' => false,
            'conversion_provider' => 'autodesk_aps',
            'supported_viewer' => 'autodesk',
            'supports_2d' => true,
            'supports_3d' => true,
            'supports_sheets' => true,
            'supports_layers' => true,
            'supports_properties' => true,
            'supports_measurement' => true,
            'supports_annotations' => true,
            'supports_comparison' => false,
            'max_size_bytes' => 1024 * 1024 * 1024,
            'icon' => 'drafting-compass',
            'fallback_message' => 'The DWG source is stored safely. Use PDF review or generate an Autodesk viewer derivative.',
        ],

        'dxf' => [
            'extension' => 'dxf',
            'label' => 'AutoCAD Interchange',
            'mime_types' => ['application/dxf', 'image/vnd.dxf', 'application/x-dxf'],
            'application' => 'autocad',
            'category' => 'source',
            'asset_type' => 'source',
            'preview_strategy' => 'autodesk-aps',
            'direct_browser_preview' => false,
            'conversion_provider' => 'autodesk_aps',
            'supported_viewer' => 'autodesk',
            'supports_2d' => true,
            'supports_3d' => true,
            'supports_sheets' => true,
            'supports_layers' => true,
            'supports_properties' => true,
            'supports_measurement' => true,
            'supports_annotations' => true,
            'supports_comparison' => false,
            'max_size_bytes' => 1024 * 1024 * 1024,
            'icon' => 'drafting-compass',
            'fallback_message' => 'The DXF source is stored safely. Use PDF review or generate an Autodesk viewer derivative.',
        ],

        // ─── RVT ────────────────────────────────────────────────────────
        'rvt' => [
            'extension' => 'rvt',
            'label' => 'Revit Project',
            'mime_types' => ['application/x-revit', 'application/revit'],
            'application' => 'revit',
            'category' => 'source',
            'asset_type' => 'source',
            'preview_strategy' => 'autodesk-aps',
            'direct_browser_preview' => false,
            'conversion_provider' => 'autodesk_aps',
            'supported_viewer' => 'autodesk',
            'supports_2d' => true,
            'supports_3d' => true,
            'supports_sheets' => true,
            'supports_layers' => true,
            'supports_properties' => true,
            'supports_measurement' => true,
            'supports_annotations' => true,
            'supports_comparison' => false,
            'max_size_bytes' => 1024 * 1024 * 1024,
            'icon' => 'building',
            'fallback_message' => 'The RVT source is stored safely. Generate an Autodesk viewer derivative or upload PDF/IFC review assets.',
        ],

        // ─── Archicad ──────────────────────────────────────────────────
        'pln' => [
            'extension' => 'pln',
            'label' => 'Archicad Project',
            'mime_types' => ['application/x-pln', 'application/x-archicad-project'],
            'application' => 'archicad',
            'category' => 'source',
            'asset_type' => 'source',
            'preview_strategy' => 'download-only',
            'direct_browser_preview' => false,
            'conversion_provider' => null,
            'supported_viewer' => null,
            'supports_2d' => false,
            'supports_3d' => false,
            'supports_sheets' => false,
            'supports_layers' => false,
            'supports_properties' => false,
            'supports_measurement' => false,
            'supports_annotations' => false,
            'supports_comparison' => false,
            'max_size_bytes' => 1024 * 1024 * 1024,
            'icon' => 'building',
            'fallback_message' => 'This is a native Archicad source file. Preview requires associated PDF layouts or IFC export.',
        ],

        'pla' => [
            'extension' => 'pla',
            'label' => 'Archicad Project Archive',
            'mime_types' => ['application/x-pla', 'application/x-archicad-archive'],
            'application' => 'archicad',
            'category' => 'source',
            'asset_type' => 'source',
            'preview_strategy' => 'download-only',
            'direct_browser_preview' => false,
            'conversion_provider' => null,
            'supported_viewer' => null,
            'supports_2d' => false,
            'supports_3d' => false,
            'supports_sheets' => false,
            'supports_layers' => false,
            'supports_properties' => false,
            'supports_measurement' => false,
            'supports_annotations' => false,
            'supports_comparison' => false,
            'max_size_bytes' => 1024 * 1024 * 1024,
            'icon' => 'archive',
            'fallback_message' => 'This is a native Archicad archive. Preview requires associated PDF layouts or IFC export.',
        ],

        // ─── SketchUp ──────────────────────────────────────────────────
        'skp' => [
            'extension' => 'skp',
            'label' => 'SketchUp Model',
            'mime_types' => ['application/x-sketchup', 'application/vnd.sketchup.skp'],
            'application' => 'sketchup',
            'category' => 'source',
            'asset_type' => 'source',
            'preview_strategy' => 'server-conversion',
            'direct_browser_preview' => false,
            'conversion_provider' => 'internal',
            'supported_viewer' => 'ifc',
            'supports_2d' => false,
            'supports_3d' => true,
            'supports_sheets' => false,
            'supports_layers' => true,
            'supports_properties' => false,
            'supports_measurement' => false,
            'supports_annotations' => false,
            'supports_comparison' => false,
            'max_size_bytes' => 500 * 1024 * 1024,
            'icon' => 'cube',
            'fallback_message' => 'The SKP source is stored safely. Export to IFC for 3D browser preview.',
        ],

        // ─── Navisworks ────────────────────────────────────────────────
        'nwd' => [
            'extension' => 'nwd',
            'label' => 'Navisworks Presenter',
            'mime_types' => ['application/x-navisworks', 'application/nwd'],
            'application' => 'navisworks',
            'category' => 'source',
            'asset_type' => 'source',
            'preview_strategy' => 'autodesk-aps',
            'direct_browser_preview' => false,
            'conversion_provider' => 'autodesk_aps',
            'supported_viewer' => 'autodesk',
            'supports_2d' => false,
            'supports_3d' => true,
            'supports_sheets' => false,
            'supports_layers' => true,
            'supports_properties' => true,
            'supports_measurement' => true,
            'supports_annotations' => true,
            'supports_comparison' => false,
            'max_size_bytes' => 1024 * 1024 * 1024,
            'icon' => 'box',
            'fallback_message' => 'The NWD source is stored safely. Generate an Autodesk viewer derivative.',
        ],

        'nwc' => [
            'extension' => 'nwc',
            'label' => 'Navisworks Cache',
            'mime_types' => ['application/x-navisworks-cache', 'application/nwc'],
            'application' => 'navisworks',
            'category' => 'source',
            'asset_type' => 'source',
            'preview_strategy' => 'autodesk-aps',
            'direct_browser_preview' => false,
            'conversion_provider' => 'autodesk_aps',
            'supported_viewer' => 'autodesk',
            'supports_2d' => false,
            'supports_3d' => true,
            'supports_sheets' => false,
            'supports_layers' => true,
            'supports_properties' => true,
            'supports_measurement' => true,
            'supports_annotations' => true,
            'supports_comparison' => false,
            'max_size_bytes' => 1024 * 1024 * 1024,
            'icon' => 'box',
            'fallback_message' => 'The NWC source is stored safely. Generate an Autodesk viewer derivative.',
        ],

        // ─── Tekla ─────────────────────────────────────────────────────
        'tekla' => [
            'extension' => 'tekla',
            'label' => 'Tekla Model',
            'mime_types' => ['application/x-tekla'],
            'application' => 'other',
            'category' => 'source',
            'asset_type' => 'source',
            'preview_strategy' => 'download-only',
            'direct_browser_preview' => false,
            'conversion_provider' => null,
            'supported_viewer' => null,
            'supports_2d' => false,
            'supports_3d' => false,
            'supports_sheets' => false,
            'supports_layers' => false,
            'supports_properties' => false,
            'supports_measurement' => false,
            'supports_annotations' => false,
            'supports_comparison' => false,
            'max_size_bytes' => 1024 * 1024 * 1024,
            'icon' => 'box',
            'fallback_message' => 'The Tekla source is stored safely. Upload IFC or PDF review derivatives for browser preview.',
        ],

        // ─── Rhino ─────────────────────────────────────────────────────
        '3dm' => [
            'extension' => '3dm',
            'label' => 'Rhino Model',
            'mime_types' => ['application/x-rhino-3dm', 'model/3dm'],
            'application' => 'other',
            'category' => 'source',
            'asset_type' => 'source',
            'preview_strategy' => 'download-only',
            'direct_browser_preview' => false,
            'conversion_provider' => null,
            'supported_viewer' => null,
            'supports_2d' => false,
            'supports_3d' => false,
            'supports_sheets' => false,
            'supports_layers' => false,
            'supports_properties' => false,
            'supports_measurement' => false,
            'supports_annotations' => false,
            'supports_comparison' => false,
            'max_size_bytes' => 1024 * 1024 * 1024,
            'icon' => 'box',
            'fallback_message' => 'The Rhino source is stored safely. Upload IFC or PDF review derivatives for browser preview.',
        ],

        // ─── DGN ───────────────────────────────────────────────────────
        'dgn' => [
            'extension' => 'dgn',
            'label' => 'MicroStation Design',
            'mime_types' => ['application/x-dgn', 'image/x-dgn'],
            'application' => 'other',
            'category' => 'source',
            'asset_type' => 'source',
            'preview_strategy' => 'server-conversion',
            'direct_browser_preview' => false,
            'conversion_provider' => 'internal',
            'supported_viewer' => 'autodesk',
            'supports_2d' => true,
            'supports_3d' => false,
            'supports_sheets' => true,
            'supports_layers' => false,
            'supports_properties' => false,
            'supports_measurement' => false,
            'supports_annotations' => false,
            'supports_comparison' => false,
            'max_size_bytes' => 500 * 1024 * 1024,
            'icon' => 'file',
            'fallback_message' => 'The DGN source is stored safely. Convert to PDF or DWG for browser preview.',
        ],

        // ─── GLTF/GLB ──────────────────────────────────────────────────
        'glb' => [
            'extension' => 'glb',
            'label' => 'GLB 3D Model',
            'mime_types' => ['model/gltf-binary', 'model/gltf+json'],
            'application' => 'other',
            'category' => 'review',
            'asset_type' => 'viewer_derivative',
            'preview_strategy' => 'ifc',
            'direct_browser_preview' => false,
            'conversion_provider' => null,
            'supported_viewer' => 'three',
            'supports_2d' => false,
            'supports_3d' => true,
            'supports_sheets' => false,
            'supports_layers' => false,
            'supports_properties' => false,
            'supports_measurement' => false,
            'supports_annotations' => false,
            'supports_comparison' => false,
            'max_size_bytes' => 500 * 1024 * 1024,
            'icon' => 'cube',
            'fallback_message' => null,
        ],

        // ─── BCF ───────────────────────────────────────────────────────
        'bcf' => [
            'extension' => 'bcf',
            'label' => 'BIM Collaboration Format',
            'mime_types' => ['application/x-bcf', 'application/vnd.bcf'],
            'application' => 'other',
            'category' => 'review',
            'asset_type' => 'supporting',
            'preview_strategy' => 'download-only',
            'direct_browser_preview' => false,
            'conversion_provider' => null,
            'supported_viewer' => null,
            'supports_2d' => false,
            'supports_3d' => false,
            'supports_sheets' => false,
            'supports_layers' => false,
            'supports_properties' => false,
            'supports_measurement' => false,
            'supports_annotations' => false,
            'supports_comparison' => false,
            'max_size_bytes' => 100 * 1024 * 1024,
            'icon' => 'message-square',
            'fallback_message' => 'BCF files contain BIM issues and viewpoints. They are not 3D models.',
        ],

        'bcfzip' => [
            'extension' => 'bcfzip',
            'label' => 'BIM Collaboration Package',
            'mime_types' => ['application/x-bcfzip', 'application/vnd.bcfzip', 'application/zip'],
            'application' => 'other',
            'category' => 'review',
            'asset_type' => 'supporting',
            'preview_strategy' => 'download-only',
            'direct_browser_preview' => false,
            'conversion_provider' => null,
            'supported_viewer' => null,
            'supports_2d' => false,
            'supports_3d' => false,
            'supports_sheets' => false,
            'supports_layers' => false,
            'supports_properties' => false,
            'supports_measurement' => false,
            'supports_annotations' => false,
            'supports_comparison' => false,
            'max_size_bytes' => 100 * 1024 * 1024,
            'icon' => 'message-square',
            'fallback_message' => 'BCF files contain BIM issues and viewpoints. They are not 3D models.',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Preview Strategies
    |--------------------------------------------------------------------------
    */
    'viewer_resolver' => [
        'priority_2d' => ['pdf', 'image', 'autodesk-aps', 'server-conversion', 'download-only'],
        'priority_3d' => ['ifc', 'autodesk-aps', 'download-only'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Asset type categories
    |--------------------------------------------------------------------------
    */
    'asset_categories' => [
        'source' => [
            'label' => 'Source File',
            'description' => 'Native authoring format. Browser preview may not be available.',
        ],
        'review_pdf' => [
            'label' => 'PDF Review',
            'description' => '2D review document.',
        ],
        'image' => [
            'label' => 'Image',
            'description' => 'Raster preview.',
        ],
        'ifc' => [
            'label' => 'IFC Model',
            'description' => 'Open BIM exchange format.',
        ],
        'viewer_derivative' => [
            'label' => 'Viewer Derivative',
            'description' => 'Generated browser-optimized derivative.',
        ],
        'supporting' => [
            'label' => 'Supporting Document',
            'description' => 'Additional reference material.',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Conversion providers
    |--------------------------------------------------------------------------
    */
    'conversion_providers' => [
        'internal' => [
            'label' => 'Internal',
            'description' => 'Server-side conversion (ImageMagick, etc.)',
            'requires_auth' => false,
        ],
        'autodesk_aps' => [
            'label' => 'Autodesk Platform Services',
            'description' => 'Autodesk Model Derivative API',
            'requires_auth' => true,
            'requires_company_consent' => true,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | External conversion policy
    |--------------------------------------------------------------------------
    */
    'external_conversion' => [
        'default_policy' => env('PROJECT_DESIGN_EXTERNAL_CONVERSION', 'disabled'),
        'allowed_policies' => ['disabled', 'administrators', 'enabled'],
    ],
];
