export const frDashboard = {
    dashboard: {
        hero: { eyebrow: 'Centre de pilotage', title: 'Operations du jour', subtitle: 'Une vue claire des projets, documents, finances et actions a traiter.' },
        actions: { refresh: 'Actualiser', monthly: 'Mensuel', newProject: 'Projet', viewAll: 'Tout voir', inbox: 'Messagerie' },
        kpis: { activeProjects: 'Projets actifs', missingDocuments: 'Documents manquants', unpaidInvoices: 'Factures impayees', todayPayments: 'Paiements du jour', blockedDossiers: 'Dossiers bloques', myTasks: 'Mes taches', pendingReviewTasks: 'A valider', unreadMessages: 'Messages non lus' },
        kpiHelpers: { totalProjects: '{count} projets au total', blockingDocuments: 'Bloque les contrats et dossiers', remainingAmount: '{amount} a recevoir', monthlyAmount: '{amount} ce mois-ci', stuckDossiers: 'Bloques a la meme etape depuis 7 jours', taskPriority: '{urgent} urgente(s), {overdue} en retard', pendingReview: 'Taches en attente de validation', allConversations: 'Toutes les conversations' },
        sections: { financeTrend: 'Flux financier', financeTrendDetail: 'Facture et encaisse sur les six derniers mois', workflow: 'Repartition projets', workflowDetail: 'Dossiers actifs par etape', focus: 'Priorite actuelle', quickActions: 'Acces rapide', actionQueue: "File d'action", actionQueueDetail: 'Apres la priorite actuelle', projects: 'Projets recents', projectsDetail: 'Dossiers recemment mis a jour', vigilance: 'Vigilance', vigilanceDetail: 'Risques a traiter', finance: 'Finance', financeDetail: 'Encaissements et relances', updates: 'Mises a jour', updatesDetail: 'Messages et activite recente' },
        quickActions: { newProject: 'Nouveau projet', uploadDocument: 'Televerser un document', createInvoice: 'Creer une facture', newClient: 'Nouveau client', newTask: 'Nouvelle tache', newConversation: 'Nouvelle conversation' },
        nextActions: { missingDocument: { title: 'Televerser un document manquant' }, unpaidInvoice: { title: 'Suivre une facture impayee' }, allClear: { title: 'Aucune action bloquante', detail: 'Le workflow est stable pour le moment.' }, due: { today: "Aujourd'hui", overdue: 'En retard', open: 'Ouverte', good: 'Bon' } },
        alerts: { overdue: { title: 'Factures en retard', detail: '{count} facture(s) en retard' }, remaining: { title: 'Solde a recevoir', detail: '{count} facture(s) impayee(s)' }, monthly: { title: 'Encaissements mensuels', detail: 'Ouvrir la synthese mensuelle' } },
        activity: { documentUpdated: 'Document mis a jour', paymentRecorded: 'Paiement enregistre', projectUpdated: 'Projet mis a jour' },
        chart: { noFinanceData: 'Aucune donnee financiere', noFinanceDataDetail: 'Les factures et paiements apparaitront ici des leur creation.', invoiced: 'Facture', collected: 'Encaisse', noActiveProjects: 'Aucun dossier actif', noActiveProjectsDetail: "La repartition apparaitra des qu'un projet sera ouvert.", active: 'actifs', dossierCount: '{count} dossier(s)' },
        states: { noRecentProject: 'Aucun projet recent.', allStable: 'Tout est stable.', noRecentUpdates: 'Aucune mise a jour recente.', documents: 'documents', days: 'j', overdue: 'Retard', urgent: 'Urgent' },
    },
};
