import { Input } from '@heroui/react';
import { IconCash, IconReceipt, IconTrash, IconWallet } from '@tabler/icons-react';
import { useState } from 'react';
import { router } from '@inertiajs/react';
import { AppButton } from '@/components/ui/AppButton';
import { AppEmptyState } from '@/components/ui/AppEmptyState';
import { AppModal } from '@/components/ui/AppModal';
import type { IntermediaryFinance } from '@/features/intermediaries/types';

const methods = [{ value: 'cash', label: 'Espèces' }, { value: 'bank_transfer', label: 'Virement bancaire' }, { value: 'check', label: 'Chèque' }, { value: 'card', label: 'Carte' }, { value: 'other', label: 'Autre' }];
const money = (value: number, currency: string) => new Intl.NumberFormat('fr-MA', { style: 'currency', currency, maximumFractionDigits: 2 }).format(value);

export function IntermediaryFinanceTab({ intermediaryId, finance, canCreate, canReverse }: { intermediaryId: number; finance: IntermediaryFinance; canCreate: boolean; canReverse: boolean }) {
    const [open, setOpen] = useState(false); const [amount, setAmount] = useState(''); const [paidAt, setPaidAt] = useState(new Date().toISOString().slice(0, 10)); const [method, setMethod] = useState('cash'); const [reference, setReference] = useState(''); const [notes, setNotes] = useState(''); const [errors, setErrors] = useState<Record<string, string>>({});
    const submit = () => router.post(`/intermediaries/${intermediaryId}/finance/payments`, { amount, paid_at: paidAt, method, reference: reference || null, notes: notes || null }, { preserveScroll: true, onSuccess: () => { setOpen(false); setAmount(''); setReference(''); setNotes(''); setErrors({}); }, onError: (e) => setErrors(e as Record<string, string>) });
    return <div className="space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-semibold text-[var(--foreground)]">Finance</h2><p className="mt-0.5 text-[11px] text-[var(--text-muted)]">Les paiements sont répartis automatiquement sur les factures les plus anciennes.</p></div>{canCreate ? <AppButton size="sm" variant="primary" isDisabled={finance.summary.remaining <= 0} onPress={() => setOpen(true)}><IconWallet size={14} />Enregistrer un paiement</AppButton> : null}</div>
        <div className="grid gap-3 sm:grid-cols-3">{[['Facturé', finance.summary.invoiced, IconReceipt], ['Payé', finance.summary.paid, IconWallet], ['Reste à payer', finance.summary.remaining, IconCash]].map(([label, value, Icon]) => <div key={String(label)} className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-4"><div className="flex items-center justify-between text-[11px] text-[var(--text-muted)]"><span>{label}</span><Icon size={15} /></div><p className="mt-2 text-lg font-semibold text-[var(--foreground)]">{money(value as number, finance.currency)}</p></div>)}</div>
        <div className="overflow-hidden rounded-xl border border-[var(--border)] bg-[var(--surface)]"><div className="border-b border-[var(--border)] px-4 py-3 text-sm font-semibold text-[var(--foreground)]">Finance par projet</div>{finance.projects.length ? <div className="divide-y divide-[var(--border)]">{finance.projects.map((project) => <button key={project.id} type="button" onClick={() => router.visit(`/dossiers/${project.id}`)} className="flex w-full items-center justify-between gap-4 px-4 py-3 text-left transition hover:bg-[var(--surface-2)]"><span className="min-w-0"><span className="block truncate text-xs font-semibold text-[var(--foreground)]">{project.name || project.number}</span><span className="block text-[10px] text-[var(--text-muted)]">{project.number} · {project.clientName || '-'} · {project.invoicesCount} facture(s)</span></span><span className="grid shrink-0 grid-cols-3 gap-4 text-right text-[11px]"><span><span className="block text-[9px] text-[var(--text-muted)]">Facturé</span><span className="font-semibold text-[var(--foreground)]">{money(project.total, finance.currency)}</span></span><span><span className="block text-[9px] text-[var(--text-muted)]">Payé</span><span className="font-semibold text-emerald-400">{money(project.paid, finance.currency)}</span></span><span><span className="block text-[9px] text-[var(--text-muted)]">Reste</span><span className="font-semibold text-amber-400">{money(project.remaining, finance.currency)}</span></span></span></button>)}</div> : <div className="p-6"><AppEmptyState title="Aucun projet attribué" /></div>}</div>
        <div className="overflow-hidden rounded-xl border border-[var(--border)] bg-[var(--surface)]"><div className="border-b border-[var(--border)] px-4 py-3 text-sm font-semibold text-[var(--foreground)]">Historique des paiements</div>{finance.batches.length ? <div className="divide-y divide-[var(--border)]">{finance.batches.map((batch) => <div key={batch.id} className="flex items-start justify-between gap-3 px-4 py-3"><div><p className="text-xs font-semibold text-[var(--foreground)]">{money(batch.amount, finance.currency)} · {batch.paidAt}</p><p className="mt-1 text-[10px] text-[var(--text-muted)]">{methods.find((option) => option.value === batch.method)?.label ?? 'Non précisé'}{batch.reference ? ` · ${batch.reference}` : ''}</p><p className="mt-1 text-[10px] text-[var(--text-muted)]">{batch.allocations.map((a) => `${a.projectName} · ${a.invoiceNumber} (${money(a.amount, finance.currency)})`).join(' · ')}</p>{batch.cancelledAt ? <p className="mt-1 text-[10px] text-[var(--danger)]">Annulé</p> : null}</div>{canReverse && batch.canCancel ? <AppButton isIconOnly compact size="sm" variant="quiet" color="danger" aria-label="Annuler le paiement" tooltip="Annuler le paiement" onPress={() => router.delete(`/intermediaries/${intermediaryId}/finance/payments/${batch.id}`, { preserveScroll: true })}><IconTrash size={14} /></AppButton> : null}</div>)}</div> : <div className="p-6"><AppEmptyState title="Aucun paiement" /></div>}</div>
        <AppModal isOpen={open} onOpenChange={setOpen} title="Paiement intermédiaire" size="sm"><div className="space-y-4"><p className="text-xs text-[var(--text-muted)]">Maximum disponible : {money(finance.summary.remaining, finance.currency)}.</p><label>Montant<Input type="number" min="0.01" step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} className="mt-1 w-full" /></label>{errors.amount ? <p className="text-xs text-[var(--danger)]">{errors.amount}</p> : null}<label>Date de paiement<Input type="date" value={paidAt} onChange={(e) => setPaidAt(e.target.value)} className="mt-1 w-full" /></label><label>Mode de paiement<select value={method} onChange={(e) => setMethod(e.target.value)} className="mt-1 h-9 w-full rounded-lg border border-[var(--border)] bg-[var(--surface)] px-2">{methods.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label>Référence (facultatif)<Input value={reference} onChange={(e) => setReference(e.target.value)} className="mt-1 w-full" /></label><label>Note (facultatif)<Input value={notes} onChange={(e) => setNotes(e.target.value)} className="mt-1 w-full" /></label><div className="flex justify-end gap-2"><AppButton variant="quiet" onPress={() => setOpen(false)}>Annuler</AppButton><AppButton variant="primary" onPress={submit}>Valider</AppButton></div></div></AppModal>
    </div>;
}
